### ISSUE TITLE
I got access to your database.

### ISSUE THREAD

**Issue by saraiva1989** [viveksinh007/heroku_demo#1]
Hi, my name is Daniel and I'm a developer in Brazil.
I got access to your database.

I work looking for vulnerability on people's websites and helping to solve for free.

        $servername   = "sql12.freemysqlhosting.net";
        $database = "sql12389559";
        $username = "sql12389559";
        $password = "IJScer634D";
        // Create connection
        $con = new mysqli($servername, $username, $password, $database);

**Comment by viveksinh007** [comment]
what should i do ?

**Comment by viveksinh007** [comment]
do i use other database for this

or can you tell me how to secure this type of information?

**Comment by saraiva1989** [comment]
@viveksinh007 

Solution 

Come on, do you want to keep this repository public?

If so, you will have to:
1 - Download the code to your local machine
2 - Delete the github repository
3 - Create a new repository
4 - upload your code, but not putting the database information in it. You upload the right connection data to your server but on github it leaves without.

Another solution that would work but is not so suitable would be to configure the server where your database is located to accept only the IP of the machine where the application is hosted. But you may have other problems if, for example, the machine where your application is hosted does not have a fixed IP.

Now if you don't want to leave the repository public, just set it to private so that no one will see the bank's connection in your code.


In summary the mistake you made was to put the connection data to the database in your code and upload it to github. So anyone who sees your repository can read your code

**Comment by viveksinh007** [comment]
Thanks for that btw it is just for practice .
For the school project .
